# Generated by Django 5.1.2 on 2026-09-25 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_exercise_dietplanhistory_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
