# Generated by Django 5.1.2 on 2026-09-25 21:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_paymenttransaction_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
                ('is_rest_day', models.BooleanField(default=False)),
                ('estimated_duration_min', models.IntegerField(default=45)),
                ('warmup_notes', models.TextField(blank=True, default='5-10 min dynamic mobility & joint activation')),
            ],
            options={
                'ordering': ['program_week', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='ProgramWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('phase_title', models.CharField(max_length=150)),
                ('focus_summary', models.TextField(blank=True)),
                ('target_rpe', models.CharField(default='RPE 7-8', max_length=50)),
            ],
            options={
                'ordering': ['program', 'week_number'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('goal', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='INTERMEDIATE', max_length=20)),
                ('days_per_week', models.IntegerField(default=4)),
                ('duration_weeks', models.IntegerField(default=8)),
                ('is_premium', models.BooleanField(default=True)),
                ('banner_gradient', models.CharField(default='linear-gradient(135deg, #1f1f1f, #0a0a0a)', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('target_sets', models.IntegerField(default=3)),
                ('target_reps', models.CharField(default='8-10', max_length=50)),
                ('rest_seconds', models.IntegerField(default=90)),
                ('target_rpe', models.DecimalField(decimal_places=1, default=8.0, max_digits=3)),
                ('coaching_cue', models.TextField(blank=True, default='')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.exercise')),
                ('program_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='app.programday')),
            ],
            options={
                'ordering': ['program_day', 'order'],
            },
        ),
        migrations.AddField(
            model_name='programday',
            name='program_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='app.programweek'),
        ),
        migrations.AddField(
            model_name='programweek',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='app.trainingprogram'),
        ),
        migrations.CreateModel(
            name='UserProgramEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(default=django.utils.timezone.localdate)),
                ('is_active', models.BooleanField(default=True)),
                ('completed_days', models.JSONField(default=list)),
                ('current_week', models.IntegerField(default=1)),
                ('current_day', models.IntegerField(default=1)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trainingprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='programday',
            unique_together={('program_week', 'day_number')},
        ),
        migrations.AlterUniqueTogether(
            name='programweek',
            unique_together={('program', 'week_number')},
        ),
    ]
